In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7815, 3127, 1490, 5673],
 [7815, 3127, 1490, 6506],
 [7815, 5978, 1490, 89],
 [742, 5469, 3723, 9517, 5329],
 [742, 5469, 3723, 9517, 5997],
 [8414, 7815, 4378, 1490, 6679],
 [7761, 1532, 4834, 9517]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7815 3127 1490 5673]
 [   0    0    0    0 7815 3127 1490 6506]
 [   0    0    0    0 7815 5978 1490   89]
 [   0    0    0  742 5469 3723 9517 5329]
 [   0    0    0  742 5469 3723 9517 5997]
 [   0    0    0 8414 7815 4378 1490 6679]
 [   0    0    0    0 7761 1532 4834 9517]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 140ms/step


array([[[ 1.61905214e-03, -3.16953212e-02,  3.40230763e-05,
          1.58999451e-02,  7.30190426e-03, -4.26427610e-02,
          2.94754989e-02,  1.45310275e-02, -2.65294202e-02,
          3.04682180e-03],
        [ 1.61905214e-03, -3.16953212e-02,  3.40230763e-05,
          1.58999451e-02,  7.30190426e-03, -4.26427610e-02,
          2.94754989e-02,  1.45310275e-02, -2.65294202e-02,
          3.04682180e-03],
        [ 1.61905214e-03, -3.16953212e-02,  3.40230763e-05,
          1.58999451e-02,  7.30190426e-03, -4.26427610e-02,
          2.94754989e-02,  1.45310275e-02, -2.65294202e-02,
          3.04682180e-03],
        [ 1.61905214e-03, -3.16953212e-02,  3.40230763e-05,
          1.58999451e-02,  7.30190426e-03, -4.26427610e-02,
          2.94754989e-02,  1.45310275e-02, -2.65294202e-02,
          3.04682180e-03],
        [ 2.97806375e-02, -4.90462556e-02, -1.28236040e-02,
          1.37872584e-02, -4.43137772e-02,  6.64523989e-03,
         -1.20861642e-02,  4.74110879e-02,  4.941034

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7815, 3127, 1490, 5673])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 39ms/step


array([[ 1.61905214e-03, -3.16953212e-02,  3.40230763e-05,
         1.58999451e-02,  7.30190426e-03, -4.26427610e-02,
         2.94754989e-02,  1.45310275e-02, -2.65294202e-02,
         3.04682180e-03],
       [ 1.61905214e-03, -3.16953212e-02,  3.40230763e-05,
         1.58999451e-02,  7.30190426e-03, -4.26427610e-02,
         2.94754989e-02,  1.45310275e-02, -2.65294202e-02,
         3.04682180e-03],
       [ 1.61905214e-03, -3.16953212e-02,  3.40230763e-05,
         1.58999451e-02,  7.30190426e-03, -4.26427610e-02,
         2.94754989e-02,  1.45310275e-02, -2.65294202e-02,
         3.04682180e-03],
       [ 1.61905214e-03, -3.16953212e-02,  3.40230763e-05,
         1.58999451e-02,  7.30190426e-03, -4.26427610e-02,
         2.94754989e-02,  1.45310275e-02, -2.65294202e-02,
         3.04682180e-03],
       [ 2.97806375e-02, -4.90462556e-02, -1.28236040e-02,
         1.37872584e-02, -4.43137772e-02,  6.64523989e-03,
        -1.20861642e-02,  4.74110879e-02,  4.94103469e-02,
        -2.